### ISSUE TITLE
Error adding tentacle package from URL

### ISSUE THREAD

**Issue by MarwanYouness** [techfreaque/octane#4]
i'm trying to add a tentacle package from URL through your-domain:5001/advanced/tentacle_packages
but it keeps throwing an error "Error during package handling, impossible to install the given tentacle package, please see logs for more details.

the logs error source: octobot_tentacles_manager.api.util.tentacles_management 
the logs error message: Exception during InstallWorker processing: (error: NotImplementedError)

full logs

2024-09-21 01:09:50 ERROR  octobot_tentacles_manager.api.util.tentacles_management logging_util.py:210      Exception during InstallWorker processing:  (error: NotImplementedError)
2024-09-21 01:10:07 ERROR  octobot_tentacles_manager.api.util.tentacles_management logging_util.py:239      
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/octobot_tentacles_manager/api/util/tentacles_management.py", line 28, in manage_tentacles
    session = authenticator.get_aiohttp_session() if authenticator and authenticator.is_logged_in() \
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/octobot_commons/authentication.py", line 84, in get_aiohttp_session
    raise NotImplementedError
NotImplementedError
2024-09-21 01:10:07 ERROR  octobot_tentacles_manager.api.util.tentacles_management logging_util.py:210      Exception during InstallWorker processing:  (error: NotImplementedError)
2024-09-21 01:10:25 ERROR  octobot_tentacles_manager.api.util.tentacles_management logging_util.py:239      
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/octobot_tentacles_manager/api/util/tentacles_management.py", line 28, in manage_tentacles
    session = authenticator.get_aiohttp_session() if authenticator and authenticator.is_logged_in() \
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/octobot_commons/authentication.py", line 84, in get_aiohttp_session
    raise NotImplementedError
NotImplementedError

OS: Ubuntu 24.04

**Comment by MarwanYouness** [comment]
Ubuntu version used was mis-matching, it worked fine on Ubuntu 20.04.
